### ISSUE TITLE
ui.scroll insert.item event handler improvement

### ISSUE THREAD

**Issue by qu1ze** [angular-ui/ui-utils#291]
I couldn't insert an element into the 1st position (0 index).
But it'd be possible with following change (560 line):
```
if ((_ref = locator - first - 1) && _ref < buffer.length)  {
   inserted.push(insert(locator, item));
   next++;
}
```

**Comment by pelizza** [comment]
This was merged on branch bower-scroll? I couldn't find that working...

**Comment by mfeingold** [comment]
The event based scroller update functionality was never documented because I hate the API. It seems to be a clunky kludge. I believe I have a better alternative now and I will publish it within a week. The event based API will stay for the sake folks like myself who already use it, but it will stay unpublished and unloved. Stay tuned.

**Comment by mfeingold** [comment]
fixed in pull request https://github.com/angular-ui/ui-utils/pull/372
