### ISSUE TITLE
Incorrect index value when scrolling

### ISSUE THREAD

**Issue by LiamK** [angular-ui/ui-utils#319]
Okay, I'm now using latest version of scroll.  The issue I'm having is that the datasource.get() function is being called the first time with an index == 1.  Is that what it's supposed to do? I'm not understanding this.
It makes three calls to the API (with count set to 3).
first call -- index == 1 (returns 3 objects)
second call -- index == 4 (returns 3 objects)
third call -- index == -2 (returns 0 objects) (I'm now preventing this one from being called at all)

I expected the first call index value to be 0.  Isn't it zero-relative?

Anyway, I decremented index before making the API call to work around that.

However, after scrolling around a bit, the index value is incremented by 3, until suddenly it goes from 15 down to 5.  Continuing to scroll backwards, it makes the call with index==2 (and then with index=-1 but I prevent that).  So it's impossible to scroll back to see the first object.  I expected that it should only increment/decrement by count (in this case 3).  Is that not the case?

What am I not understanding here, or is this a bug?

**Comment by mfeingold** [comment]
The math involved in deciding what items to return is a bit confusing. Unfortunately there is not much to be done to simplify it because it is the direct result of how unpredictable the scrollbars can be. 

To make life easier I would suggest to follow the pattern published in the examples i.e. [here](https://github.com/Hill30/NGScroller/blob/master/src/examples/persistentScroll.coffee)

**Comment by flekschas** [comment]
And what about added the possibility to start counting at zero? I mean that makes more sense since when you want to get the first element in JS (or any other programming language) you access it with index zero, e.g. `[1, 2, 3][0]`. Sure people can work around that but this behaviour is very unintuitive (I just notice it by accident) and why not allow an attribute that simple defines the index of the first value?
