### ISSUE TITLE
HELP(ui-jq)TypeError: Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by idpocky** [angular-ui/ui-utils#408]
[Help]Something's wrong with this line:
```javascript
elm[attrs.uiJq].apply(elm, createLinkOptions());
```
I want to load `bootstrap-filestyle` by `ui-jq`. However...
I tried:
- elm: it's an object ([input#filestyle...]).
- attrs.uiJq: 'filestyle'(the name I defined).

**Comment by PowerKiKi** [comment]
UI.Utils modules was split in individuals repositories. If still valid, please consider re-submitting the issue on its dedicated issue tracker.

See the [README for details](https://github.com/angular-ui/ui-utils#readme).

**Comment by iamdeadman** [comment]
So how to fix this error, how do I check which individual repo i have to use ?

**Comment by PowerKiKi** [comment]
@iamdeadman see the [README for details](https://github.com/angular-ui/ui-utils#readme). ui-jq was not "forked" because it was not worth the effort, because of general lack of interest (from maintainers and users). Latest version is still available here via `bower install angular-ui-utils#jq-0.2.3`, but I am afraid the issue is still not solved.
