### ISSUE TITLE
Demo page issues

### ISSUE THREAD

**Issue by blowsie** [angular-ui/ui-utils#421]
Where is the repo for the http://angular-ui.github.io/ website? 
There are several broken links, and I would also like to restest several of the closed issues on the ?new? demo page.

Thanks

**Comment by blowsie** [comment]
Also, where can I find the other modules, have they been removed from the new version??

>~~alias~~
event
~~format~~
~~highlight~~
~~ie-shiv~~
~~include~~
indeterminate
~~inflector~~
~~jq~~
~~keypress~~
mask
~~reset~~
~~route~~
~~scroll~~
~~scrollfix~~
~~showhide~~
~~unique~~
validate

**Comment by johnsto** [comment]
I, too, am wondering where they've gone...

**Comment by PowerKiKi** [comment]
you can find the code over there: https://github.com/angular-ui/angular-ui.github.com. Beware that it just have been updated to reflect new organization (and remove deprecated things).

* ``scrollfix`` was renamed as [scrollpoint](https://github.com/angular-ui/ui-scrollpoint)
* ``scroll`` was suggested to be renamed as ``virtualize`` but since the project actually live out of AngularUI organization, we are waiting for @mfeingold and @dhilt opinion on that matter

Everything else was judged not much relevant anymore. And they will be left as is unless there is a clear interest from many people. So you can still access their "old" version from this repository, but it is likely that they will not evolve anymore. At least not in this repository anymore.

As for demo page of each modules, they are unfortunately not directly available online anymore. But you can use a service like http://htmlpreview.github.io to view them. Please refer to http://angular-ui.github.io/

**Comment by blowsie** [comment]
@PowerKiKi Thanks for the info. Whilst I can see the need to clean up, I personally feel this is a bit of a loss to the community.

I hope enough people can encourage you to bring them back :+1:
