### ISSUE TITLE
Bower 2.0.0 version does not contain build

### ISSUE THREAD

**Issue by SamMorrowDrums** [angular-ui/ui-utils#423]
`Bower install --save angular-ui-utils` has resolved to:

"angular-ui-utils": "~2.0.0"

However, there is no dist folder, or minified JS file.

![screen shot 2015-07-20 at 17 06 39](https://cloud.githubusercontent.com/assets/4811358/8780566/b5bbf64e-2f01-11e5-9dd4-e435b5a6c80c.png)

**Comment by SamMorrowDrums** [comment]
OK, I apologise, it seems need to install it with the bower tag. Perhaps this should be on the Readme.MD here.

**Comment by PowerKiKi** [comment]
Not directly related to your issue, but it made me realize that v1.0.0 and v2.0.0 were messed up. `angular-ui-utils` were split in individual modules and thus modules will be installed as dependencies from now on. This is now correctly reflected in the brand new v3.0.0.

Also I suggest you only install the required individuals modules, rather than `angular-ui-utils`. This package will become obsolete in the future and will end up being destroyed in the far future.
