### ISSUE TITLE
unique filter

### ISSUE THREAD

**Issue by matthieusieben** [angular-ui/ui-utils#425]
So, it seems the `unique` filter did not seem relevant. I get that (not really a UI feature).

Do you recommend another package that includes this feature ? Or any of the features that were dropped for that matter.

**Comment by PowerKiKi** [comment]
Nothing specific to recommend, but you can still use the "old" one (`bower install angular-ui-utils#unique-0.2.3`). It will not disappear anytime soon. And if you realize that it actually needs some modification later one, then you can consider forking, and/or contribute to angular-ui as a standalone module.

The reason we didn't split it in a standalone module is not because the code is of poor quality, but rather because it _seems_ that it is not used by enough people to be worth the time to maintain. If there is a strong interest, it could be revived.
